// src/config/ideTutorials.js
// Tutorial step configurations for IDE-based ROS2 lessons

/**
 * Tutorial for Creating Package lesson
 * Guides user through creating a ROS2 package using visual blocks
 */
export const createPackageTutorial = [
  {
    title: "Welcome to the ROS2 IDE! 👋",
    text: "This interactive IDE will guide you through creating your first ROS2 package. We'll use visual blocks to generate the ros2 pkg create command, then build it in the terminal.",
    position: "center",
    target: null,
    buttonText: "Let's Start!",
  },
  {
    title: "Block Palette",
    text: "This is your block palette. It contains all the visual blocks you can use. Different tabs organize blocks by category.",
    position: "right",
    target: ".ide-test__palette",
    offset: 30,
    scrollIntoView: true,
  },
  {
    title: "Navigate to ROS Tab",
    text: "Click on the 'ROS' tab in the palette to see ROS2-specific blocks like 'Create Package'.",
    position: "bottom",
    target: ".categorized-palette__tab[data-category='ROS']",
    offset: 20,
    backdropClickable: false,
    hideControls: true,
    tip: "Click the ROS tab to continue",
  },
  {
    title: "Create Package Block",
    text: "Great! Now you can see the 'Create Package' block. Drag it onto the canvas to start building your package configuration.",
    position: "right",
    target: ".categorized-palette__block[data-type='createPackage']",
    offset: 20,
    tip: "Drag the 'Create Package' block to the canvas",
  },
  {
    title: "Canvas Workspace",
    text: "This is your visual programming canvas. You can drag blocks here, connect them together, and configure them to generate ROS2 commands.",
    position: "left",
    target: ".ide-test__canvas-content",
    offset: 30,
  },
  {
    title: "Configure the Package",
    text: "Click on the 'Create Package' block you just placed. You can edit the package name, node name, and dependencies directly in the block.",
    position: "bottom",
    target: ".rf-node[data-type='createPackage']",
    offset: 20,
    tip: "Try changing the package name to 'my_robot_pkg'",
  },
  {
    title: "Input Blocks (Optional)",
    text: "You can also use Text and List blocks from the Input tab to connect dynamic values. But for now, editing the block directly is fine!",
    position: "right",
    target: ".categorized-palette__tab[data-category='Input']",
    offset: 20,
  },
  {
    title: "Output Blocks",
    text: "Now navigate to the 'Output' tab. This contains the 'Convert to Code' block that will generate the actual terminal command.",
    position: "bottom",
    target: ".categorized-palette__tab[data-category='Output']",
    offset: 20,
    tip: "Click on the Output tab",
  },
  {
    title: "Convert to Code Block",
    text: "Drag the 'Convert to Code' block onto the canvas. This will generate the ros2 pkg create command from your package configuration.",
    position: "right",
    target: ".categorized-palette__block[data-type='toCode']",
    offset: 20,
    tip: "Drag this block to the canvas",
  },
  {
    title: "Connect the Blocks",
    text: "Connect the 'Create Package' block to the 'Convert to Code' block by dragging from the output handle (right side) to the input handle (left side).",
    position: "top",
    target: ".rf-node[data-type='createPackage'] .react-flow__handle-right",
    offset: 20,
    tip: "Drag from the circle on the right of 'Create Package' to the circle on the left of 'Convert to Code'",
  },
  {
    title: "View Generated Command",
    text: "Once connected, the 'Convert to Code' block shows the generated command. You can copy it or click 'Run in Terminal' to execute it directly!",
    position: "left",
    target: ".rf-node[data-type='toCode']",
    offset: 30,
  },
  {
    title: "Terminal Panel",
    text: "Now let's switch to the terminal to run the command. Click on the Terminal tab at the top of the IDE.",
    position: "bottom",
    target: ".ide-test__tab[data-tab='terminal']",
    offset: 20,
    tip: "Click the Terminal tab",
    hideControls: true,
  },
  {
    title: "Execute the Command",
    text: "The terminal is now active. Type or paste the generated command, or click 'Run in Terminal' from the Convert to Code block. This will create your ROS2 package in the src/ folder.",
    position: "top",
    target: ".terminal",
    offset: 30,
    warning: "Make sure you're in the workspace directory before running the command",
  },
  {
    title: "Build the Package",
    text: "After creating the package, you need to build it with colcon. Type 'colcon build' in the terminal and press Enter. This compiles your package and makes it ready to use.",
    position: "top",
    target: ".terminal",
    offset: 30,
    tip: "Run: colcon build",
  },
  {
    title: "Source the Workspace",
    text: "Finally, source your workspace with 'source install/setup.bash'. This tells ROS2 where to find your newly built package.",
    position: "top",
    target: ".terminal",
    offset: 30,
    tip: "Run: source install/setup.bash",
  },
  {
    title: "Package Created! 🎉",
    text: "Congratulations! You've created and built your first ROS2 package using the visual IDE. You can now see it in the file explorer and use it to create publisher and subscriber nodes!",
    position: "center",
    target: null,
    buttonText: "Finish Tutorial",
  },
];

/**
 * Tutorial for Creating Publishers lesson
 * Guides user through creating ROS2 publisher nodes
 */
export const createPublisherTutorial = [
  {
    title: "Creating ROS2 Publishers 📡",
    text: "In this lesson, you'll learn to create publisher nodes that send messages to ROS2 topics. We'll use visual blocks to configure the publisher, then generate and test the code!",
    position: "center",
    target: null,
    buttonText: "Start Learning",
  },
  {
    title: "ROS2 Tab",
    text: "Navigate to the 'ROS2' tab in the block palette. This contains the Publisher and Subscriber blocks.",
    position: "bottom",
    target: ".categorized-palette__tab[data-category='ROS2']",
    offset: 20,
    tip: "Click the ROS2 tab",
    hideControls: true,
  },
  {
    title: "ROS2 Publisher Block",
    text: "This is the Publisher block! It lets you configure everything about your publisher: topic name, message type, publish frequency, and the data to send.",
    position: "right",
    target: ".categorized-palette__block[data-type='rosPublisher']",
    offset: 20,
    tip: "Drag the Publisher block to the canvas",
  },
  {
    title: "Configure Your Publisher",
    text: "Click on the Publisher block to configure it. You can set the topic name (e.g., '/chatter'), choose the message type (String, Int32, etc.), and set how fast it publishes.",
    position: "bottom",
    target: ".rf-node[data-type='rosPublisher']",
    offset: 20,
    tip: "Try setting topic to '/chatter' and message type to 'String'",
  },
  {
    title: "Publisher Name",
    text: "Give your publisher a unique name. This will be used as the Python class name and helps identify the node when it's running.",
    position: "left",
    target: ".ros-publisher-node__field input[type='text']",
    offset: 20,
  },
  {
    title: "Message Type Selection",
    text: "Choose the message type carefully! Common types include String (text), Int32 (numbers), Float64 (decimals), and Twist (robot movement). Each type has specific uses.",
    position: "left",
    target: ".ros-publisher-node__grid-2",
    offset: 20,
    tip: "std_msgs/String is great for beginners!",
  },
  {
    title: "Publish Frequency",
    text: "The frequency controls how often messages are sent (in Hz). 1.0 = 1 message per second, 10.0 = 10 messages per second. Start with 1.0 for testing.",
    position: "left",
    target: ".ros-publisher-node input[placeholder='1.0']",
    offset: 20,
  },
  {
    title: "Optional: Data Input",
    text: "You can connect a Text block from the Input tab to provide custom data. Or just configure the data directly in the publisher block!",
    position: "right",
    target: ".categorized-palette__tab[data-category='Input']",
    offset: 20,
  },
  {
    title: "Generate Publisher Code",
    text: "Now connect your Publisher block to a 'Convert to Code' block (from Output tab). This generates a complete Python ROS2 publisher node file!",
    position: "top",
    target: ".rf-node[data-type='rosPublisher'] .react-flow__handle-right",
    offset: 20,
    tip: "Connect to a 'Convert to Code' block",
  },
  {
    title: "File Explorer",
    text: "Your generated publisher code will be saved to your ROS2 package. You can see it appear in the file explorer after generating.",
    position: "right",
    target: ".ide-test__explorer",
    offset: 30,
  },
  {
    title: "Save to Package",
    text: "Click 'Generate Publisher Code' or 'Save File' to create the Python file in your package directory (src/your_package/your_package/).",
    position: "bottom",
    target: ".btn--primary",
    offset: 20,
    warning: "Make sure you created a package first in lesson 3!",
  },
  {
    title: "Update setup.py",
    text: "Important! You need to add an entry point in setup.py for your publisher. Open setup.py and add your publisher node to the console_scripts list.",
    position: "left",
    target: ".ide-test__explorer",
    offset: 30,
    tip: "Add: 'publisher_node = your_pkg.publisher_node:main'",
  },
  {
    title: "Build Your Package",
    text: "Switch to the Terminal tab and run 'colcon build' to compile your package with the new publisher node.",
    position: "bottom",
    target: ".ide-test__tab[data-tab='terminal']",
    offset: 20,
    tip: "Run: colcon build",
  },
  {
    title: "Run Your Publisher",
    text: "After building, source the workspace ('source install/setup.bash') and run your publisher with 'ros2 run your_package publisher_node'. You should see messages being published!",
    position: "top",
    target: ".terminal",
    offset: 30,
    tip: "Run: ros2 run your_pkg publisher_node",
  },
  {
    title: "Test with ros2 topic",
    text: "Open another terminal (or press Ctrl+C to stop the publisher) and run 'ros2 topic echo /chatter' to see the messages your publisher is sending!",
    position: "top",
    target: ".terminal",
    offset: 30,
    tip: "Run: ros2 topic echo /chatter",
  },
  {
    title: "Publisher Created! 🎉",
    text: "Excellent work! You've created a working ROS2 publisher node. Try changing the message type, frequency, or data and rebuild to see how it affects the output!",
    position: "center",
    target: null,
    buttonText: "Complete Tutorial",
  },
];

/**
 * Tutorial for Creating Subscribers lesson
 * Guides user through creating ROS2 subscriber nodes
 */
export const createSubscriberTutorial = [
  {
    title: "Creating ROS2 Subscribers 📥",
    text: "Subscribers listen to topics and process incoming messages. You'll create a subscriber node that receives messages from the publisher you created earlier!",
    position: "center",
    target: null,
    buttonText: "Let's Build!",
  },
  {
    title: "ROS2 Subscriber Block",
    text: "Navigate to the ROS2 tab and find the 'ROS2 Subscriber' block. This will help you create a node that listens to messages.",
    position: "right",
    target: ".categorized-palette__block[data-type='rosSubscriber']",
    offset: 20,
    tip: "Drag the Subscriber block to the canvas",
  },
  {
    title: "Configure Topic Name",
    text: "Set the topic name to match your publisher! If your publisher sends to '/chatter', your subscriber should listen to '/chatter'. Topic names must match exactly.",
    position: "left",
    target: ".ros-subscriber-node input[placeholder='/chatter']",
    offset: 20,
    warning: "Topic and message type must match the publisher!",
  },
  {
    title: "Message Type Match",
    text: "Select the SAME message type as your publisher. If the publisher uses String, the subscriber must also use String. Mismatched types won't communicate!",
    position: "left",
    target: ".ros-subscriber-node__grid-2",
    offset: 20,
  },
  {
    title: "Subscriber Name",
    text: "Give your subscriber a unique name. This helps identify it when debugging and allows you to run multiple subscribers if needed.",
    position: "left",
    target: ".ros-subscriber-node input[type='text']",
    offset: 20,
  },
  {
    title: "Generate Subscriber Code",
    text: "Connect the Subscriber block to a 'Convert to Code' block to generate the complete Python subscriber node code.",
    position: "top",
    target: ".rf-node[data-type='rosSubscriber'] .react-flow__handle-right",
    offset: 20,
    tip: "Connect to Convert to Code block",
  },
  {
    title: "Save Subscriber File",
    text: "Generate and save the subscriber code to your package directory. It will create a file like 'subscriber_node.py' or 'listener_node.py'.",
    position: "bottom",
    target: ".btn--primary",
    offset: 20,
  },
  {
    title: "Update setup.py Again",
    text: "Don't forget to add the subscriber entry point in setup.py! Add something like 'subscriber_node = your_pkg.subscriber_node:main' to the console_scripts.",
    position: "left",
    target: ".ide-test__explorer",
    offset: 30,
    tip: "Add subscriber to console_scripts in setup.py",
  },
  {
    title: "Rebuild Package",
    text: "Run 'colcon build' in the terminal to compile your package with both publisher and subscriber nodes.",
    position: "top",
    target: ".terminal",
    offset: 30,
    tip: "Run: colcon build",
  },
  {
    title: "Test Communication",
    text: "Now for the exciting part! You need TWO terminals: one for the publisher, one for the subscriber. Let's test them together!",
    position: "top",
    target: ".terminal",
    offset: 30,
    warning: "You'll need to run publisher and subscriber simultaneously",
  },
  {
    title: "Run Publisher First",
    text: "In one terminal, source the workspace and run your publisher: 'ros2 run your_pkg publisher_node'. You should see it publishing messages.",
    position: "top",
    target: ".terminal",
    offset: 30,
    tip: "Terminal 1: ros2 run your_pkg publisher_node",
  },
  {
    title: "Run Subscriber",
    text: "In the terminal (or use background with &), run the subscriber: 'ros2 run your_pkg subscriber_node'. You should now see it receiving the publisher's messages!",
    position: "top",
    target: ".terminal",
    offset: 30,
    tip: "Terminal 2: ros2 run your_pkg subscriber_node",
  },
  {
    title: "Press Ctrl+C to Stop",
    text: "Use Ctrl+C to stop running nodes. The terminal now supports real-time output streaming, so you can see messages as they arrive!",
    position: "top",
    target: ".terminal",
    offset: 30,
    tip: "Ctrl+C kills the running process",
  },
  {
    title: "Verify Communication",
    text: "Use 'ros2 topic list' to see active topics, 'ros2 topic info /chatter' to see publisher/subscriber counts, and 'ros2 topic hz /chatter' to check message frequency.",
    position: "top",
    target: ".terminal",
    offset: 30,
  },
  {
    title: "Subscriber Working! 🎉",
    text: "Congratulations! You've created a complete ROS2 publisher-subscriber system. This is the foundation of how ROS2 nodes communicate. Try creating more complex message types next!",
    position: "center",
    target: null,
    buttonText: "Tutorial Complete",
  },
];

/**
 * Tutorial for Creating LIDAR Subscriber
 * Guides user through subscribing to QCar LIDAR sensor data
 */
export const createLidarSubscriberTutorial = [
  {
    title: "Subscribing to LIDAR Sensor Data 🎯",
    text: "The QCar has a 360° LIDAR sensor that publishes distance measurements. You'll create a subscriber to receive this data and detect obstacles!",
    position: "center",
    target: null,
    buttonText: "Start Tutorial",
  },
  {
    title: "Understanding LIDAR Data",
    text: "LIDAR publishes to the /scan topic using the sensor_msgs/LaserScan message type. This includes arrays of distance measurements, angle information, and timing data.",
    position: "center",
    target: null,
    buttonText: "Next",
  },
  {
    title: "Create LIDAR Subscriber Node",
    text: "Navigate to the ROS2 tab and drag a Subscriber block to the canvas. We'll configure it to listen to the LIDAR sensor.",
    position: "right",
    target: ".categorized-palette__block[data-type='rosSubscriber']",
    offset: 20,
    tip: "Drag the Subscriber block to the canvas",
  },
  {
    title: "Configure Topic Name",
    text: "Set the topic name to '/scan'. This is where the QCar LIDAR publishes its sensor data.",
    position: "left",
    target: ".ros-subscriber-node input[placeholder='/chatter']",
    offset: 20,
    tip: "Enter: /scan",
  },
  {
    title: "Select Message Type",
    text: "Choose 'sensor_msgs/LaserScan' as the message type. This is the standard ROS2 message for LIDAR data containing range measurements.",
    position: "left",
    target: ".ros-subscriber-node__grid-2",
    offset: 20,
    warning: "Must use LaserScan for LIDAR data!",
  },
  {
    title: "Name Your Node",
    text: "Name your subscriber something like 'lidar_subscriber' or 'obstacle_detector'. This will be the node name shown in ROS2.",
    position: "left",
    target: ".ros-subscriber-node input[type='text']",
    offset: 20,
  },
  {
    title: "Generate Code",
    text: "Connect the subscriber to a 'Convert to Code' block to generate the Python node. The code will include callback handling for LaserScan messages.",
    position: "top",
    target: ".rf-node[data-type='rosSubscriber'] .react-flow__handle-right",
    offset: 20,
  },
  {
    title: "Processing LIDAR Data",
    text: "The generated callback receives a LaserScan message. You can access: msg.ranges (distance array), msg.angle_min/max (scan angles), and msg.range_min/max (distance limits).",
    position: "center",
    target: null,
    buttonText: "Understand",
  },
  {
    title: "Find Closest Obstacle",
    text: "In the callback, you can use min(msg.ranges) to find the closest obstacle distance. Add logic to warn if something is closer than 0.5 meters!",
    position: "top",
    target: ".terminal",
    offset: 30,
    tip: "Add: if min(msg.ranges) < 0.5: self.get_logger().warn('Obstacle detected!')",
  },
  {
    title: "Build and Test",
    text: "Save the file, build your package with 'colcon build', source the workspace, and run your node. If the QCar LIDAR is active, you'll see real-time distance data!",
    position: "top",
    target: ".terminal",
    offset: 30,
    tip: "Run: ros2 run your_pkg lidar_subscriber",
  },
  {
    title: "Visualize in RViz2",
    text: "Open RViz2 and add a LaserScan display with topic '/scan' to see the LIDAR data visually. You'll see a point cloud representing obstacles around the QCar!",
    position: "center",
    target: null,
    buttonText: "Got it!",
  },
  {
    title: "LIDAR Subscriber Complete! 🎉",
    text: "You've successfully subscribed to the QCar LIDAR sensor! Try processing the data to detect obstacles in specific directions or calculate safe navigation zones.",
    position: "center",
    target: null,
    buttonText: "Finish",
  },
];

/**
 * Tutorial for Creating Camera Subscriber
 * Guides user through subscribing to QCar camera feeds
 */
export const createCameraSubscriberTutorial = [
  {
    title: "Subscribing to Camera Data 📷",
    text: "The QCar has 5 cameras: 1 RGB camera and 4 CSI cameras (front, right, back, left). You'll create a subscriber to receive and process camera images!",
    position: "center",
    target: null,
    buttonText: "Let's Start",
  },
  {
    title: "QCar Camera Topics",
    text: "Camera topics: /camera/image_raw (RGB), /camera/csi_front/image_raw, /camera/csi_right/image_raw, /camera/csi_back/image_raw, /camera/csi_left/image_raw. All use sensor_msgs/Image message type.",
    position: "center",
    target: null,
    buttonText: "Next",
  },
  {
    title: "Create Camera Subscriber",
    text: "Drag a Subscriber block from the ROS2 tab. We'll configure it to receive images from the front camera.",
    position: "right",
    target: ".categorized-palette__block[data-type='rosSubscriber']",
    offset: 20,
    tip: "Drag Subscriber to canvas",
  },
  {
    title: "Set Camera Topic",
    text: "Set the topic to '/camera/csi_front/image_raw' to subscribe to the front camera. You can create separate subscribers for each camera if needed!",
    position: "left",
    target: ".ros-subscriber-node input[placeholder='/chatter']",
    offset: 20,
    tip: "Enter: /camera/csi_front/image_raw",
  },
  {
    title: "Select Image Message Type",
    text: "Choose 'sensor_msgs/Image' as the message type. This contains the image data, encoding format, dimensions, and timestamp.",
    position: "left",
    target: ".ros-subscriber-node__grid-2",
    offset: 20,
  },
  {
    title: "Name Your Camera Node",
    text: "Name it something like 'camera_subscriber' or 'front_camera_listener'. This helps identify which camera feed you're processing.",
    position: "left",
    target: ".ros-subscriber-node input[type='text']",
    offset: 20,
  },
  {
    title: "Generate Camera Subscriber Code",
    text: "Connect to 'Convert to Code' to generate the subscriber. The callback will receive Image messages with pixel data.",
    position: "top",
    target: ".rf-node[data-type='rosSubscriber'] .react-flow__handle-right",
    offset: 20,
  },
  {
    title: "Process Image Data",
    text: "The Image message contains: msg.width, msg.height, msg.encoding (RGB8, BGR8, etc.), and msg.data (raw pixel array). You can log image dimensions to verify it's working!",
    position: "center",
    target: null,
    buttonText: "Understand",
  },
  {
    title: "Optional: Use cv_bridge",
    text: "For image processing, install cv_bridge to convert ROS Images to OpenCV format. Add 'from cv_bridge import CvBridge' and use bridge.imgmsg_to_cv2(msg) in your callback.",
    position: "center",
    target: null,
    buttonText: "Good to know",
    warning: "Requires: pip install opencv-python",
  },
  {
    title: "Build and Run",
    text: "Build your package, source the workspace, and run the camera subscriber. If the camera is publishing, you'll see image messages arriving!",
    position: "top",
    target: ".terminal",
    offset: 30,
    tip: "Run: ros2 run your_pkg camera_subscriber",
  },
  {
    title: "Visualize with rqt_image_view",
    text: "To see the camera feed visually, run 'ros2 run rqt_image_view rqt_image_view' and select your camera topic. You'll see live video from the QCar!",
    position: "center",
    target: null,
    buttonText: "Try it!",
  },
  {
    title: "Monitor Multiple Cameras",
    text: "You can create multiple subscribers (one for each camera) in the same node, or create separate nodes for each camera feed. Great for 360° visual awareness!",
    position: "center",
    target: null,
    buttonText: "Interesting!",
  },
  {
    title: "Camera Subscriber Complete! 🎉",
    text: "You're now receiving camera data from the QCar! Next, try processing images for lane detection, object recognition, or motion detection.",
    position: "center",
    target: null,
    buttonText: "Finish Tutorial",
  },
];

// Export all tutorials
export default {
  createPackage: createPackageTutorial,
  createPublisher: createPublisherTutorial,
  createSubscriber: createSubscriberTutorial,
  createLidarSubscriber: createLidarSubscriberTutorial,
  createCameraSubscriber: createCameraSubscriberTutorial,
};
