# Generated by Django 5.1.3 on 2025-11-17 20:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Canvas',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canvases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Canvas',
                'verbose_name_plural': 'Canvases',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkspaceFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('path', models.CharField(help_text="Relative path from canvas root (e.g., 'src/my_robot/urdf/robot.urdf')", max_length=512)),
                ('file_type', models.CharField(choices=[('file', 'File'), ('directory', 'Directory')], default='file', max_length=10)),
                ('content', models.TextField(blank=True, help_text='File content (empty for directories)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('canvas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='workspace.canvas')),
            ],
            options={
                'ordering': ['path'],
                'unique_together': {('canvas', 'path')},
            },
        ),
    ]
